# Generated by Django 5.2 on 2025-04-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Método')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('needs_change', models.BooleanField(default=False, verbose_name='Precisa de troco?')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor pago')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Troco')),
                ('transaction_code', models.CharField(blank=True, max_length=100, verbose_name='Código (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='restaurants.order')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.paymentmethod')),
            ],
        ),
    ]
