# Generated by Django 5.2 on 2025-04-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_order_card_alter_carditem_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
    ]
