# Generated by Django 5.2 on 2025-04-22 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_order_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor pago')),
                ('payment_method', models.CharField(choices=[('CA', 'Dinheiro'), ('CR', 'Crédito'), ('DE', 'Débito'), ('PX', 'Pix'), ('OT', 'Outro')], max_length=2, verbose_name='Forma de pagamento')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Pago em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurants.card')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payments', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Recebimento no Cartão',
                'verbose_name_plural': 'Recebimentos nos Cartões',
                'ordering': ['-paid_at'],
            },
        ),
    ]
