# Generated by Django 5.2 on 2025-04-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_cardpayment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('id', 'restaurant', 'number')},
        ),
    ]
