# Generated by Django 5.2 on 2025-04-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_card_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco a devolver'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido em dinheiro'),
        ),
    ]
