# Generated by Django 5.2 on 2025-04-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_cardpayment_change_amount_cardpayment_paid_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardpayment',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Recebimento', 'verbose_name_plural': 'Recebimentos'},
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='change_amount',
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido (se diferente)'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor da venda'),
        ),
    ]
