# Generated by Django 5.2 on 2025-04-26 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_cardpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardpayment',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Recebimento no Cartão', 'verbose_name_plural': 'Recebimentos nos Cartões'},
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='received_amount',
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco a devolver'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido em dinheiro'),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor pago'),
        ),
    ]
