# Generated by Django 5.2 on 2025-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_alter_cardpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chave Pix'),
        ),
    ]
