# Generated by Django 5.2 on 2025-04-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
