# Generated by Django 5.2 on 2025-04-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantidade em estoque'),
        ),
    ]
