# Generated by Django 5.2 on 2025-04-28 19:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_alter_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Fornecedor')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Nota de Entrada',
                'verbose_name_plural': 'Notas de Entrada',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.menuitem')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.stockentry')),
            ],
            options={
                'verbose_name': 'Item da Nota de Entrada',
                'verbose_name_plural': 'Itens da Nota de Entrada',
            },
        ),
    ]
