# Generated by Django 5.2 on 2025-05-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_stockentry_stockentryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['number'], 'verbose_name': 'Comanda', 'verbose_name_plural': 'Comandas'},
        ),
        migrations.AlterModelOptions(
            name='cardpayment',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Recebimento da Comanda', 'verbose_name_plural': 'Recebimento das Comandas'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__order', 'name'], 'verbose_name': 'Item do Cardápio', 'verbose_name_plural': 'Itens do Cardápio'},
        ),
        migrations.AddField(
            model_name='carditem',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Pronto?'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Número da Comanda'),
        ),
    ]
