# Generated by Django 5.2 on 2025-05-09 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_card_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Dono'), ('cashier', 'Caixa'), ('waiter', 'Garçom')], default='cashier', max_length=20)),
            ],
            options={
                'verbose_name': 'Usuário do Restaurante',
                'verbose_name_plural': 'Usuários do Restaurante',
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['restaurant', 'is_active'], name='restaurants_restaur_984644_idx'),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_users', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='restaurantuser',
            index=models.Index(fields=['user', 'restaurant'], name='restaurants_user_id_7f7731_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantuser',
            unique_together={('user', 'restaurant')},
        ),
    ]
