# Generated by Django 5.2 on 2025-05-13 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0027_restaurantuser_card_restaurants_restaur_984644_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantidade'),
        ),
    ]
