# Generated by Django 5.2 on 2025-05-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_remove_payment_method_remove_payment_order_and_more'),
        ('restaurants', '0029_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        # Add this to remove the constraint


        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]