# Generated by Django 5.2 on 2025-04-21 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
        ('restaurants', '0007_alter_order_customer_alter_order_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.paymentmethod', verbose_name='Método de pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.order', verbose_name='Pedido'),
        ),
    ]
