# Generated by Django 5.2 on 2025-05-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_alter_payment_method_alter_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
